// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Session struct {
	ID                 int64           `json:"id"`
	SessionID          string          `json:"session_id"`
	InstanceID         string          `json:"instance_id"`
	Hostname           string          `json:"hostname"`
	Timestamp          string          `json:"timestamp"`
	ExitReason         sql.NullString  `json:"exit_reason"`
	PermissionMode     sql.NullString  `json:"permission_mode"`
	WorkingDirectory   sql.NullString  `json:"working_directory"`
	GitBranch          sql.NullString  `json:"git_branch"`
	ClaudeVersion      sql.NullString  `json:"claude_version"`
	DurationSeconds    sql.NullInt64   `json:"duration_seconds"`
	UserPrompts        sql.NullInt64   `json:"user_prompts"`
	AssistantResponses sql.NullInt64   `json:"assistant_responses"`
	ToolCalls          sql.NullInt64   `json:"tool_calls"`
	ToolsBreakdown     sql.NullString  `json:"tools_breakdown"`
	FilesAccessed      sql.NullString  `json:"files_accessed"`
	FilesModified      sql.NullString  `json:"files_modified"`
	InputTokens        sql.NullInt64   `json:"input_tokens"`
	OutputTokens       sql.NullInt64   `json:"output_tokens"`
	ThinkingTokens     sql.NullInt64   `json:"thinking_tokens"`
	CacheReadTokens    sql.NullInt64   `json:"cache_read_tokens"`
	CacheWriteTokens   sql.NullInt64   `json:"cache_write_tokens"`
	EstimatedCostUsd   sql.NullFloat64 `json:"estimated_cost_usd"`
	ErrorsCount        sql.NullInt64   `json:"errors_count"`
	Model              sql.NullString  `json:"model"`
	Summary            sql.NullString  `json:"summary"`
}
