// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type LimitEvent struct {
	ID             int64           `json:"id"`
	Timestamp      string          `json:"timestamp"`
	LimitType      string          `json:"limit_type"`
	ResetTime      sql.NullString  `json:"reset_time"`
	SessionsCount  sql.NullInt64   `json:"sessions_count"`
	InputTokens    sql.NullInt64   `json:"input_tokens"`
	OutputTokens   sql.NullInt64   `json:"output_tokens"`
	ThinkingTokens sql.NullInt64   `json:"thinking_tokens"`
	TotalCostUsd   sql.NullFloat64 `json:"total_cost_usd"`
}

type Session struct {
	ID                 int64           `json:"id"`
	SessionID          string          `json:"session_id"`
	InstanceID         string          `json:"instance_id"`
	Hostname           string          `json:"hostname"`
	Timestamp          string          `json:"timestamp"`
	ExitReason         sql.NullString  `json:"exit_reason"`
	PermissionMode     sql.NullString  `json:"permission_mode"`
	WorkingDirectory   sql.NullString  `json:"working_directory"`
	GitBranch          sql.NullString  `json:"git_branch"`
	ClaudeVersion      sql.NullString  `json:"claude_version"`
	DurationSeconds    sql.NullInt64   `json:"duration_seconds"`
	UserPrompts        sql.NullInt64   `json:"user_prompts"`
	AssistantResponses sql.NullInt64   `json:"assistant_responses"`
	ToolCalls          sql.NullInt64   `json:"tool_calls"`
	ToolsBreakdown     sql.NullString  `json:"tools_breakdown"`
	FilesAccessed      sql.NullString  `json:"files_accessed"`
	FilesModified      sql.NullString  `json:"files_modified"`
	InputTokens        sql.NullInt64   `json:"input_tokens"`
	OutputTokens       sql.NullInt64   `json:"output_tokens"`
	ThinkingTokens     sql.NullInt64   `json:"thinking_tokens"`
	CacheReadTokens    sql.NullInt64   `json:"cache_read_tokens"`
	CacheWriteTokens   sql.NullInt64   `json:"cache_write_tokens"`
	EstimatedCostUsd   sql.NullFloat64 `json:"estimated_cost_usd"`
	ErrorsCount        sql.NullInt64   `json:"errors_count"`
	Model              sql.NullString  `json:"model"`
	Summary            sql.NullString  `json:"summary"`
	Rating             sql.NullInt64   `json:"rating"`
	PromptSpecificity  sql.NullInt64   `json:"prompt_specificity"`
	TaskCompletion     sql.NullInt64   `json:"task_completion"`
	CodeConfidence     sql.NullInt64   `json:"code_confidence"`
	Notes              sql.NullString  `json:"notes"`
	LimitMessage       sql.NullString  `json:"limit_message"`
}

type SessionTag struct {
	SessionID string         `json:"session_id"`
	TagName   string         `json:"tag_name"`
	CreatedAt sql.NullString `json:"created_at"`
}

type Tag struct {
	Name     string `json:"name"`
	Category string `json:"category"`
	Color    string `json:"color"`
}
